### ISSUE TITLE
Cannot read property ‘top’ of undefined

### ISSUE THREAD

**Issue by thecodeinfluencer** [StartBootstrap/startbootstrap-freelancer#228]
Im getting this error:

freelancer.js:43 Uncaught TypeError: Cannot read property 'top' of undefined
    at navbarCollapse (freelancer.js:43)
    at freelancer.js:50
    at freelancer.js:65

**Comment by muhammadumerfarooq** [comment]
go to freelancer.js at line 43 which has the following line of code `if($("#mainNav").offset().top() > 100) `

then add another condition in it `if ($("#mainNav").length>0 && $("#mainNav").offset().top() > 100)`

hope that it will solve the issue

**Comment by mbenjerminne** [comment]
Thanks

**Comment by davidtmiller** [comment]
It looks like this issue occurred when you removed the `#mainNav` element. Is that correct?

The fix is good, but I'm not sure if it's something I want to bring into the theme itself since it's such a situation fix and removing the main navigation is not something that I think most users will go and do.
