### ISSUE TITLE
Problem with responsivity

### ISSUE THREAD

**Issue by agurai** [StartBootstrap/startbootstrap-freelancer#290]
Hello,

I write here because I have an issue with the template Freelancer on smaller resolutions.
When going under 574px, and even sometimes on bigger resolutions, there's some white space on the right.
https://prnt.sc/v3y8yj
I can't find what's the problem, I tried to change things but even adding a "container" class doesn't change a thing.
I saw the margins are the same but doesn't look like it even on big resolutions. I think it might be a major general problem.
https://prnt.sc/v3yax8

Thanks for your time

**Comment by davidtmiller** [comment]
Anything with a static width will add that whitespace if the width is greater than the screen width. In your example, the culprit is the word "Bootstrap" in the `h1` element. Make that font size smaller and you'll see that shift go away.

That being said, I will be taking a comb over all of the themes at some point making sure they respond well down to a 320px width. Anything with a viewport below 320px width is extremely rare, so we won't be supporting below that screen width.

Hopefully this helps explain things!
